### ISSUE TITLE
No scripts registered

### ISSUE THREAD

**Issue by js802025** [felixludos/digi-diplo#1]
fig h says there are no scripts registered is there a way to register them

**Comment by felixludos** [comment]
I can't seem to reproduce that error. Are you calling "fig -h" from inside the repo directory?

**Comment by js802025** [comment]
yes, i just downloaded it too. hmm

**Comment by js802025** [comment]
when i run the script it also says it doesnt work

**Comment by felixludos** [comment]
Which script are you trying to run, and what exactly is the error?

**Comment by js802025** [comment]
`    raise artifact_errors[atype](name)
omnifig.errors.MissingScriptError: diplo-new`

im attempting to make a new game but none of the other scripts registered either:
````
Specify a registered script name to run

  - No scripts registered -

`
```

**Comment by js802025** [comment]
Is there some file I have to run first?

**Comment by js802025** [comment]
what version of python did  you use?

**Comment by felixludos** [comment]
There's no other file you have to run, all the scripts should get registered on startup (when running any "fig" command). Any python version 3.6+ should work.
Unfortunately, about half the scripts in the readme aren't currently working (although `diplo-new` actually should be fine), and I'm generally in the middle of a major refactor.
If you are interested in the Col-dip map, we should talk offline (contact me from the col-dip server) because setting that map up requires a few additional files anyway.
Otherwise, can you confirm you're using omnifig version 0.5.12?

**Comment by js802025** [comment]
yes, im not sure whats wrong however when i tried to run one of the files it says no module named omnibelt installed when it is. this could be preventing commands to run.

**Comment by felixludos** [comment]
`omnibelt` is definitely a required dependency for omnifig (you can install it with `pip install omnibelt`), I'm surprised it didn't install automatically when you installed omnifig. Anyway, make sure you have that all dependencies of omnifig are installed (you should be able run `import omnifig` and `import omnibelt` without issue in the repl). If that works, then try running `fig -h` from some other directory (eg. home) and you should see no scripts registered, but also no other error. Then try running `fig -h` from the same directory as the `.fig.yaml` file, and you should get this output:
```
Usage: fig [-<meta>] <script> [<configs>...] [--<args>]

+--------+
| script |
+--------+
Specify a registered script name to run
Name               Description
-----------------  ---------------------------------------------------
mapping            Collects map adjacencies for diplomacy
node-locs          Set positions for nodes in a Diplomacy map
collect-fills      Collects points to fill on map for control
collect-pos        Collects Pixel coordinates on the map for diplomacy
diplo-new          Create a new Diplomacy game
diplo-step         Take a Diplomacy step
parse-vdip         Parse a vdiplomacy game log to yaml
diplo-traj         Resolve a sequence of actions from an initial state
map-identities     -
view-idents        -
match-names        -
categorize-fields  -
edge-finder        -
map-attribute      -
parse-col-actions  -
viz-map            -

+------+
| meta |
+------+
Optional meta arguments (usually specified with a single letter)
Code    Name    Description
------  ------  -------------------------
-d      debug   Switch to debug mode
-h      help    Display this help message

+---------+
| configs |
+---------+
Specify any registered configs to merge

Registered configs: automap/col, automap/new, automap/parse, automap/scs, automap/step, automap/viz, colors/classic, colors/colonial, colors/vdip, debug, test/collect-fills, test/collect-pos, test/diplo-new, test/diplo-step, test/diplo-traj, test/mapping, test/node-locs, test/parse-vdip, test/render-traj, test/render, viz/classic ... [21 items]

+------+
| args |
+------+
Any additional arguments specified manually
as key-value pairs (keys with "--")

**Comment by js802025** [comment]
hmm i tried that and pip says it's installed then i tried downloading src and importing manually which works for idle but not the fig...

**Comment by felixludos** [comment]
But the fig help command runs without error? That may also mean there’s some other dependency missing and that’s causing the registration at startup to fail (although that should generally raise an error).
I updated the requirements with a few newer ones so make sure you have those installed as well.
Next make sure you can importing `src/` from the repl in the same dir with `import src`
 If that works, then you could try making sure all the contents of src were correctly imported and the scripts were registered with `omnifig.view_scripts()`

**Comment by js802025** [comment]
ok, I also just lined python3 to python cmd which i think was the part messing up the requirements. when I try `omnifig.view_scripts()` I get this:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'omnifig' has no attribute 'view_scripts'
```
so im not sure
and running `create_game.py` results in this:
`    from .. import util
ImportError: attempted relative import with no known parent package`

**Comment by js802025** [comment]
ok so update, I reran the entire thing on repl and im having the same problem. Here's the repl:
https://replit.com/@JackAdee1/digi-diplo

**Comment by felixludos** [comment]
I was able to reproduce the error using replit. Make sure both `omnifig` and `omnibelt` are updated to the new versions (0.6 and 0.4.5 respectively), and also that `pydip` is installed from github (https://github.com/aparkins/pydip) because the default version on `pip` is outdated.
With that, I'm able to get the correct output with `fig -h` on replit (so all the scripts register correctly).

**Comment by js802025** [comment]
Ok

**Comment by js802025** [comment]
Ok scripts have registered but when running fthis error is called: `omnifig.errors.MissingParameterError: graph-path`

**Comment by felixludos** [comment]
Omni-fig has been updated, and digi-diplo has been refactored, so this issue has most likely been fixed.
